/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import java.awt.Toolkit;
import Model.NhanVien;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author sangt
 */
public class Main extends javax.swing.JFrame {

    NhanVien nv;

    /**
     * Creates new form Main
     */
    public Main(NhanVien nv) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/logo20.png")));
        setResizable(false);
        setLocationRelativeTo(null);
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss dd-M-yyyy");
                Date d;
                while (true) {
                    d = new Date();
                    Main.lb_dongho.setText(sdf.format(d).toString());
                }
            }
        });
        t.start();
        this.nv = nv;
        if (nv.getVaitro() == 1) {
            btn_nhanvien.setEnabled(false);
            btn_thongke.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        pn_main = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_chuyende = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_nguoihoc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_khoahoc = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_nhanvien = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btn_hocvien = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btn_thongke = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btn_doimatkhau = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btn_xuattailieu = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btn_dangxuat = new javax.swing.JButton();
        pn_statusbar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_dongho = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pn_logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");

        jToolBar1.setRollover(true);

        btn_chuyende.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_chuyende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/chuyende24.png"))); // NOI18N
        btn_chuyende.setText("Chuyên đề");
        btn_chuyende.setFocusable(false);
        btn_chuyende.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_chuyende.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_chuyende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chuyendeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_chuyende);
        jToolBar1.add(jSeparator1);

        btn_nguoihoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_nguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/student24.png"))); // NOI18N
        btn_nguoihoc.setText("Người học");
        btn_nguoihoc.setFocusable(false);
        btn_nguoihoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nguoihoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nguoihocActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nguoihoc);
        jToolBar1.add(jSeparator2);

        btn_khoahoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_khoahoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khoahoc24.png"))); // NOI18N
        btn_khoahoc.setText("Khóa học");
        btn_khoahoc.setFocusable(false);
        btn_khoahoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_khoahoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_khoahoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoahocActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_khoahoc);
        jToolBar1.add(jSeparator4);

        btn_nhanvien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_nhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nhanvien24.png"))); // NOI18N
        btn_nhanvien.setText("Nhân viên");
        btn_nhanvien.setFocusable(false);
        btn_nhanvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nhanvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhanvienActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nhanvien);
        jToolBar1.add(jSeparator5);

        btn_hocvien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_hocvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hocvien24.png"))); // NOI18N
        btn_hocvien.setText("Học viên");
        btn_hocvien.setFocusable(false);
        btn_hocvien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_hocvien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_hocvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hocvienActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_hocvien);
        jToolBar1.add(jSeparator6);

        btn_thongke.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thongke.png"))); // NOI18N
        btn_thongke.setText("Thống kê");
        btn_thongke.setFocusable(false);
        btn_thongke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_thongke.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongkeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_thongke);
        jToolBar1.add(jSeparator7);

        btn_doimatkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_doimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/doimatkhau.png"))); // NOI18N
        btn_doimatkhau.setText("Đổi mật khẩu");
        btn_doimatkhau.setFocusable(false);
        btn_doimatkhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doimatkhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_doimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doimatkhauActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_doimatkhau);
        jToolBar1.add(jSeparator8);

        btn_xuattailieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_xuattailieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tailieu24.png"))); // NOI18N
        btn_xuattailieu.setText("Tài liệu");
        btn_xuattailieu.setFocusable(false);
        btn_xuattailieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_xuattailieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_xuattailieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuattailieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_xuattailieu);
        jToolBar1.add(jSeparator9);

        btn_dangxuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btn_dangxuat.setText("Đăng xuất");
        btn_dangxuat.setFocusable(false);
        btn_dangxuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dangxuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_dangxuat);

        pn_statusbar.setBackground(new java.awt.Color(255, 255, 255));
        pn_statusbar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Hệ thống quản lý đào tạo");

        lb_dongho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_dongho.setText("01:13:00 28/9/2021");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dongho.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/i.png"))); // NOI18N

        javax.swing.GroupLayout pn_statusbarLayout = new javax.swing.GroupLayout(pn_statusbar);
        pn_statusbar.setLayout(pn_statusbarLayout);
        pn_statusbarLayout.setHorizontalGroup(
            pn_statusbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_statusbarLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_dongho))
        );
        pn_statusbarLayout.setVerticalGroup(
            pn_statusbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
            .addComponent(jLabel2)
            .addGroup(pn_statusbarLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(pn_statusbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lb_dongho)))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo450.png"))); // NOI18N

        javax.swing.GroupLayout pn_logoLayout = new javax.swing.GroupLayout(pn_logo);
        pn_logo.setLayout(pn_logoLayout);
        pn_logoLayout.setHorizontalGroup(
            pn_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_logoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(83, 83, 83))
        );
        pn_logoLayout.setVerticalGroup(
            pn_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_logoLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
            .addComponent(pn_statusbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(pn_statusbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhanvienActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Ui.NhanVien(nv).setVisible(true);
    }//GEN-LAST:event_btn_nhanvienActionPerformed

    private void btn_hocvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hocvienActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new HocVien(nv).setVisible(true);
    }//GEN-LAST:event_btn_hocvienActionPerformed

    private void btn_chuyendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chuyendeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ChuyenDe(nv).setVisible(true);
    }//GEN-LAST:event_btn_chuyendeActionPerformed

    private void btn_doimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doimatkhauActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DoiMatKhau(nv).setVisible(true);
    }//GEN-LAST:event_btn_doimatkhauActionPerformed

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btn_dangxuatActionPerformed

    private void btn_nguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nguoihocActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new NguoiHoc(nv).setVisible(true);
    }//GEN-LAST:event_btn_nguoihocActionPerformed

    private void btn_khoahocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoahocActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new KhoaHoc(nv).setVisible(true);
    }//GEN-LAST:event_btn_khoahocActionPerformed

    private void btn_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongkeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ThongKe(nv).setVisible(true);
    }//GEN-LAST:event_btn_thongkeActionPerformed

    private void btn_xuattailieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuattailieuActionPerformed
        OpenGioiThieu();
    }//GEN-LAST:event_btn_xuattailieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chuyende;
    private javax.swing.JButton btn_dangxuat;
    private javax.swing.JButton btn_doimatkhau;
    private javax.swing.JButton btn_hocvien;
    private javax.swing.JButton btn_khoahoc;
    private javax.swing.JButton btn_nguoihoc;
    private javax.swing.JButton btn_nhanvien;
    private javax.swing.JButton btn_thongke;
    private javax.swing.JButton btn_xuattailieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JLabel lb_dongho;
    private javax.swing.JPanel pn_logo;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_statusbar;
    // End of variables declaration//GEN-END:variables

    private void OpenGioiThieu() {
       try {
            Desktop.getDesktop().browse(new File("GioiThieu/SOF2041_TaiLieu.pdf").toURI());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi mở phải giới thiệu!");
        }
    }
}
